options:
  prev_tag: "versio-prev"

projects:
  - name: "commonspec"
    root: "libs/commonspec"
    id: 1
    tag_prefix: "commonspec"
    labels: npm
    version:
      file: "package.json"
      json: "version"

  - name: "root"
    id: 2
    tag_prefix: "root"
    labels: npm
    version:
      file: "package.json"
      json: "version"

  - name: "bl-web-static-site"
    root: "apps/blacklion/static-site"
    id: 3
    tag_prefix: "bl-web-static-site"
    labels: npm
    version:
      file: "package.json"
      json: "version"

  - name: "bl-web-frontend"
    root: "apps/blacklion/frontend"
    id: 4
    tag_prefix: "bl-web-frontend"
    labels: npm
    version:
      file: "package.json"
      json: "version"

  - name: "bl-web-api"
    root: "apps/blacklion/web-api"
    id: 5
    tag_prefix: "bl-web-api"
    labels: npm
    version:
      file: "package.json"
      json: "version"

sizes:
  use_angular: true
  fail: ["*"]
